### ISSUE TITLE
Please publish sources to maven central

### ISSUE THREAD

**Issue by the-james-burton** [t0xa/gelfj#100]
There are no sources in here...
http://repo1.maven.org/maven2/org/graylog2/gelfj/1.1.14/ 

Could you please publish sources to maven central which will make it much easier to use when developing?

Thanks, James

**Comment by happyyangyuan** [comment]
Up!  Please too!

**Comment by t0xa** [comment]
Will do in 1.1.15. Should be published shortly.

**Comment by the-james-burton** [comment]
That's awesome, thank you!

**Comment by t0xa** [comment]
v1.1.15 published, sources are included.

**Comment by the-james-burton** [comment]
Looks perfect to me, thanks very much!
