### ISSUE TITLE
regular jar also contains dependencies

### ISSUE THREAD

**Issue by the-james-burton** [t0xa/gelfj#101]
You regular jar..
http://repo1.maven.org/maven2/org/graylog2/gelfj/1.1.14/gelfj-1.1.14.jar

...seems to also contain dependencies just like this one does...
http://repo1.maven.org/maven2/org/graylog2/gelfj/1.1.14/gelfj-1.1.14-jar-with-dependencies.jar

Could you please ensure that the regular jar does not contain dependencies? This will make it easier to to work with maven and allow us to specify different log4j versions at runtime.

Thanks, James

**Comment by t0xa** [comment]
Understood.

**Comment by t0xa** [comment]
v1.1.15 published. Please check.

**Comment by the-james-burton** [comment]
Looks great, I can see the two separate jars and they have the correct contents.

Thanks again,
James
