### ISSUE TITLE
Support arrays

### ISSUE THREAD

**Issue by dploeger** [t0xa/gelfj#119]
It currently isn't possible to add additional fields of an array type.

For example, this:

```
log4j.appender.graylog2.additionalFields={'tags': ['first_tag', 'next_tag', 'some_tag']}
```

leads to this:
Caused by: java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.lang.String

It would be nice, if the appender would support that.

**Comment by joschi** [comment]
@dploeger The GELF specification doesn't support arrays, so it wouldn't be too useful if gelfj emitted them.

**Comment by dploeger** [comment]
Erm, okay. I'm a bit stumped, that it works, though. 😊 Thanks.
