### ISSUE TITLE
GelfMessageFactory (1.1.12) does not handle MDC correctly

### ISSUE THREAD

**Issue by martin-walsh** [t0xa/gelfj#92]
GelfMessageFactory is assuming that GelfAppender is used directly and not wrapped in an AsyncAppender.  The MDC access breaks if the used with AsyncAppender.  The fix is pretty simple:

Replace
```
    // Get MDC and add a GELF field for each key/value pair
    Map<String, Object> mdc = MDC.getContext();
```
with:
```
    // Get MDC and add a GELF field for each key/value pair
    Map<String, Object> mdc = event.getProperties();
```

If there is an AsyncAppender, Log4J will have populated the mdcCopy within the LoggingEvent already.  If there is no AsyncAppender, Log4J will populate the mdcCopy when getProperties() is invoked, and return the MDC.

**Comment by martin-walsh** [comment]
Added pull request.  All existing tests pass including the MDC test case in GelfAppenderTest

**Comment by t0xa** [comment]
Hi Martin,

Thanks a lot for your contribution. I will release new version shortly.

Anton
